enableInlineBuilds: true

enableInlineHunks: true

nodeLinker: node-modules

npmRegistryServer: '${REGISTRY_URL:-https://mirrors.cloud.tencent.com/npm}'

unsafeHttpWhitelist:
  - '*.tencent.com'

yarnPath: .yarn/releases/yarn-2.4.2.cjs
